# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "findingpatterns"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = false

enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

replyByEmail = false

mainSections = ["posts", "projects"]
# robots = ""

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
backgroundImageWidth = 1200

# defaultBackgroundImage = "/img/background.svg"
# defaultFeaturedImage = "/img/featured.svg"
# defaultSocialImage = "/img/blowfish_banner.png"
hotlinkFeatureImage = false
imagePosition = "50% 50%"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

#giteaDefaultServer = "https://git.fsfe.org"
#forgejoDefaultServer = "https://v11.next.forgejo.org"

fingerprintAlgorithm = "sha512" # Valid values are "sha512" (default), "sha384", "sha256"

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur
  showTitle = true
  showAppearanceSwitcher = false
  showLanguageSwitcher = false

[footer]
  showMenu = false
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, hero, card, background, custom
  # homepageImage = "/img/iceland.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 6
  showMoreLink = false
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background
  disableHeroImageFilter = false # only used when layout equals hero

[article]
  showDate = false
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = false
  showAuthorBottom = false
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  # editURL = "https://github.com/nunocoracao/blowfish/tree/main/exampleSite/content"
  editAppendPath = false
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = false
  invertPagination = false
  showReadingTime = true
  showTableOfContents = false
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = false
  # sharingLinks =  [ "linkedin", "twitter", "bluesky", "reddit", "email"] # [ "linkedin", "twitter", "bluesky", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email", "line"]
  showZenMode = false

[list]
  showHero = false
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = true
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[firebase]
  #apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
  #authDomain = "blowfish-21fff.firebaseapp.com"
  #projectId = "blowfish-21fff"
  #storageBucket = "blowfish-21fff.appspot.com"
  #messagingSenderId = "60108104191"
  #appId = "1:60108104191:web:039842ebe1370698b487ca"
  #measurementId = "G-PEDMYR1V0K"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = false

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = false

[buymeacoffee]
  identifier = "nunocoracao"
  globalWidget = false
  globalWidgetMessage = ""
  globalWidgetColor = "#FFDD00"
  globalWidgetPosition = "right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[rssnext]
  # feedId = ""
  # userId = ""

[advertisement]
  # adsense = ""

[assets]
  customCSS = ["css/custom.css"]